version: '3.8'

services:

  mysqlbackempresa:
    image: mysql:latest
    container_name: mysqlbackempresa
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BackEmpresa

  mysqlbackweb:
    image: mysql:latest
    container_name: mysqlbackweb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BackWeb

  mysqlbackweb1:
    image: mysql:latest
    container_name: mysqlbackweb1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BackWeb1

  eurekaserver:
    image: rubenyera12/eureka-server-application
    container_name: eurekaserver
    ports:
      - "8761:8761"

  apigateway:
    image: rubenyera12/gateway
    container_name: apigateway
    ports:
      - "8083:8083"
    links:
      - "eurekaserver"
    depends_on:
      - "eurekaserver"
    environment:
      eureka.client.service-url.defaultZone: http://eurekaserver:8761/eureka

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  backempresaapplication:
    image: rubenyera12/backempresaapplication
    container_name: backempresaapplication
    ports:
      - "8080:8080"
    depends_on:
      - "eurekaserver"
      - "apigateway"
      - "kafka"
      - "zookeeper"
      - "mysqlbackempresa"
    environment:
      spring.datasource.url: jdbc:mysql://mysqlbackempresa:3306/BackEmpresa
      spring.kafka.bootstrap-servers: kafka:9092
      eureka.client.service-url.defaultZone: http://eurekaserver:8761/eureka

  backwebapplication:
    image: rubenyera12/backwebapplication
    container_name: backwebapplication
    ports:
      - "8081:8081"
    depends_on:
      - "eurekaserver"
      - "apigateway"
      - "kafka"
      - "zookeeper"
      - "mysqlbackweb"
    environment:
      spring.datasource.url: jdbc:mysql://mysqlbackweb:3306/BackWeb
      spring.kafka.bootstrap-servers: kafka:9092
      eureka.client.service-url.defaultZone: http://eurekaserver:8761/eureka

  backweb1application:
    image: rubenyera12/backwebapplication
    container_name: backweb1application
    ports:
      - "8082:8082"
    depends_on:
      - "eurekaserver"
      - "apigateway"
      - "kafka"
      - "zookeeper"
      - "mysqlbackweb1"
    environment:
      server.port: 8082
      group: BACKWEB1
      spring.datasource.url: jdbc:mysql://mysqlbackweb1:3306/BackWeb1
      spring.kafka.bootstrap-servers: kafka:9092
      eureka.client.service-url.defaultZone: http://eurekaserver:8761/eureka